name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: windows-latest
    
    steps:
    - name: addmodules
      uses: actions/checkout@v3
      with:
       submodules: 'true'
       
    - name: compileProject
      run: clang -Og -pedantic -Wall -Werror -Wextra -Wimplicit-atomic-properties -Woverlength-strings -Wshadow Translator.c "C-MyBasics\MyBasics.c" -c && clang -Og -pedantic -Wall -Werror -Wextra -Wimplicit-atomic-properties -Woverlength-strings -Wshadow -Wno-unused-function "Miscellaneous\Analysis\wdanalysis.c" -c



